### ISSUE TITLE
2.10.0 breaks my Datadog metrics

### ISSUE THREAD

**Issue by slisaasquatch** [DataDog/java-dogstatsd-client#112]
So this is how I currently setup my `StatsDClient`:
```java
new NonBlockingStatsDClient("", "localhost", 8125);
```
I just tried updating the version to 2.10.0, and I've tried using the old deprecated constructor and then this:
```java
new NonBlockingStatsDClientBuilder().prefix("").hostname("localhost").port(8125).build();
```
And Datadog metrics stopped showing up if I use either of those. And as soon as I downgraded to 2.9.0, metrics started working again.
So am I doing something wrong? Is there some additional thing I need to do in 2.10.0?
Thanks!

**Comment by truthbk** [comment]
@slisaasquatch thanks for reporting this, I will try to reproduce and get back to you.

**Comment by truthbk** [comment]
It seems to be working for me, I have verified both build methods with both a unit test and a small standalone app. Can you give us a little more information about your app? Are you setting any client-supported environment variables?

Would it be possible for you to set netcat to listen on a port of your choosing:
```
nc -u -l -p 76543
```

And then send the metrics there, and see if you see any incoming metrics in that port?

```
NonBlockingStatsDClient client = new NonBlockingStatsDClientBuilder().prefix("").hostname("localhost").port(76543).build();

// do client things, for example:
client.gauge("value", 42);
```

and see what comes out on the netcat side. 

Let me know, and I'll try to help fix whatever's broken @slisaasquatch 

Thank you!

**Comment by slisaasquatch** [comment]
Thanks for your reply.

I'm not setting environment variables. I'm just using a `datadog.yaml` config file.

Here's the file content if that helps:

```yaml
api_key: "myApiKey"
dd_url: https://app.datadoghq.com
bind_host: localhost
additional_endpoints: {}
tags: []
dogstatsd_non_local_traffic: false
histogram_aggregates:
  - max
  - median
  - avg
  - count
histogram_percentiles:
  - "0.95"
use_dogstatsd: true
log_level: INFO
logs_enabled: true
process_config:
  enabled: "true"
  intervals: {}
  blacklist_patterns: []
  process_dd_url: https://process.datadoghq.com
log_file: /var/log/datadog/agent.log
log_to_syslog: false
apm_config:
  enabled: true
  apm_non_local_traffic: false
```

I'll try upgrading to 2.10.0 and then run netcat and see how it goes. In the meantime if there's any specific info you are looking for, please let me know.
