### ISSUE TITLE
Periodical dd-task-scheduler errors - Unable to create StatsD client - localhost:8125

### ISSUE THREAD

**Issue by drobakowski** [DataDog/java-dogstatsd-client#191]
Hi there,

I'm not sure if the following errors origins from this library or [datadog-lambda-java](https://github.com/DataDog/datadog-lambda-java), but we're seeing a lot of dd-task-scheduler errors from Java lambdas like this:

![](https://user-images.githubusercontent.com/81381/161951945-ed8a1014-964b-4b46-be2a-4e4b9d8d017c.png)

```sh
[dd.trace 2022-04-18 22:16:49:700 +0000] [dd-task-scheduler] ERROR datadog.communication.monitor.DDAgentStatsDConnection - Unable to create StatsD client - localhost:8125
```

We are using version `1.4.4` of this library in combination with the latest [serverless-datadog-plugin - v5.0.0](https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.0.0) which uses the lambda layer `v21` of [datadog-lambda-extension](https://github.com/DataDog/datadog-lambda-extension) and `v4` of the `dd-trace-java` layer and `java11`. For instrumenting things we've followed the official DataDog documentation. The errors doesn't seem to be specific to the Serverless plugin, as we also get this errors when we integrate the layers and configs directly without the plugin. Also the log level doesn't seem to take effect, as we're seeing the logs unaggregated on INFO level, despite the fact that we have configured logLevel: warn or DD_LOG_LEVEL: WARN.

Our serverless.yml config looks like this:
```yaml
...
provider:
  environment:
    DD_ENV: ${self:provider.stage}
    DD_SERVICE: ${self:service}
    DD_TRACE_SAMPLE_RATE: ${self:custom.datadogTracingSampleRate.${opt:stage, self:provider.stage}}
    DD_VERSION: ${git:sha1}
...
custom:
  datadogTracingSampleRate:
    dev: 1.0
    int: 0.8
    prod: 1.0
  ...
  datadog:
    addExtension: true
    apiKey: ${ssm:.../apiKey}
    site: datadoghq.eu

    flushMetricsToLogs: true
    addLayers: true
    logLevel: warn
    enableTags: true
    injectLogContext: true
    integrationTesting: false
```

Any ideas what we could do to fix the error?
